



export const LOAD_ALBUM_SUCCESS = "LOAD_ALBUM_SUCCESS"
export const LOAD_PHOTOS_SUCCESS = "LOAD_PHOTOS_SUCCESS";
export const LOAD_PHOTOS_FAILED = "LOAD_PHOTOS_FAILED";
export const BUY = "BUY"


