



export const LOAD_ALBUM_SUCCESS = "LOAD_ALBUM_SUCCESS"
export const LOAD_REVIEWS_SUCCESS = "LOAD_REVIEWS_SUCCESS";
export const LOAD_REVIEWS_FAILED = "LOAD_REVIEWS_FAILED";
export const SUBMIT_NEW_REVIEW = "SUBMIT_NEW_REVIEW"
export const BUY = "BUY"
export const CHECKOUT = "CHECKOUT"

